const fs = require('fs');
const path = require('path');

const jsonPath = path.join('C:', 'Users', 'User', 'Projects', 'sanper-vision-astro', 'src', 'data', 'landing_pages.json');
const data = JSON.parse(fs.readFileSync(jsonPath, 'utf8'));

const updates = {
    "pergola-systeme/bioklimatisch": {
        block_1_content: `<h3>Technik, die begeistert: Der Kamineffekt gegen Hitzestau</h3>
<p>Die meisten herkömmlichen Terrassenüberdachungen aus Glas oder Polycarbonat stoßen im Hochsommer schnell an ihre Grenzen. Unter dem dichten Dach entsteht ein Treibhauseffekt, der den Aufenthalt unerträglich macht. Eine bioklimatische Pergola von Sanper mit stufenlos verstellbaren Aluminium-Lamellen löst dieses Problem durch physikalische Perfektion: den Kamineffekt.</p>
<p>In der Hitze des Tages öffnen Sie die Lamellen einfach leicht per Knopfdruck um bis zu 120 Grad. Die warme, aufsteigende Luft kann sofort nach oben entweichen, während von den Seiten angenehm kühle Frischluft nachströmt. So entsteht eine völlig natürliche, sanfte Zirkulation. Sie sitzen selbst bei 35 Grad im Schatten und genießen ein perfektes Wohlfühlklima, ohne von stehender Hitze erschlagen zu werden.</p>
<p>Zusätzlich sind die Systeme mit intelligenten Sensoren ausgestattet. Sobald der Regen- oder Schneesensor Alarm schlägt, schließen die wartungsfreien, bürstenlosen Motoren die Lamellen absolut spaltfrei. Das Dach wird zu 100% wasserdicht. Das anfallende Regenwasser wird unsichtbar über ein integriertes Gefälle innerhalb der Lamellen in eine rundum laufende Regenrinne abgeführt und durch die massiven Aluminium-Pfosten direkt in den Boden geleitet. Keine nassen Möbel, keine hässlichen Außenrohre.</p>`,
        block_2_content: `<h3>Statik und extreme Belastbarkeit: Gebaut für Stürme und Winter</h3>
<p>Wer in eine bioklimatische Pergola investiert, erwartet extreme Langlebigkeit. Während viele fernöstliche Baumarkt-Sätze mit fatalen Profilstärken von nur 1.4 mm bis 1.8 mm arbeiten, nutzt Sanper für seine Konstruktionen massives, stranggepresstes Aluminium der Legierung EN AW-6060. Unsere Profile besitzen eine Materialstärke von teilweise 3 bis 5 Millimetern. Das Ergebnis ist eine statische Verlässlichkeit, die ihresgleichen sucht.</p>
<ul>
<li><strong>Windlast bis 140 km/h:</strong> Die massive Bauweise der Pfosten und die aerodynamische Form der geschlossenen Lamellen trotzen selbst extremen Orkanböen, ohne dass das System Schaden nimmt oder knarzt. Gegebenenfalls schützt sich die Anlage durch Sensoren komplett autark vor Überlast.</li>
<li><strong>Schneelast bis 400 kg/m²:</strong> Schnee ist schwer und kann Dächer zum Einsturz bringen. Die Sanper-Lamellen tragen eine extreme Last. Bei vorhergesagtem Extrem-Schneefall können die Lamellen zudem auf 90° aufgestellt werden, damit die Schneemassen widerstandslos hindurchfallen und nicht auf dem Dach lasten. Weiterer Härtetest: Die Frostüberwachung verhindert das Festfrieren der beweglichen Teile.</li>
<li><strong>Wartungsfreiheit:</strong> Verbaut werden ausschließlich rostfreie Edelstahlbolzen und selbstschmierende Messinglager für eine absolut verschleißfreie Rotation.</li>
</ul>
<p>Mit Sanper kaufen Sie nicht einfach nur einen Sonnenschutz. Sie erwerben ein in Deutschland konzipiertes, hochpräzises Ingenieursbauwerk, direkt ab Werk und komplett ohne teure Zwischenhändler. Die Installation übernimmt das hauseigene Montageteam, mit 5 Jahren Vollgarantie auf alle tragenden und mechanischen Bauteile.</p>`
    },
    "pergola-systeme/terrasse": {
        block_1_content: `<h3>Die Wandanbau-Pergola als perfekte Wohnraumerweiterung</h3>
<p>Die Nahtstelle zwischen Haus und Garten ist der wichtigste Raum für das familiäre Zusammenleben. Mit einer Terrassen-Pergola, die direkt an die Hauswand montiert wird, schaffen Sie eine echte Verschmelzung von Drinnen und Draußen. Sie betreten Ihre Terrasse, als würden Sie ein weiteres Wohnzimmer betreten – trockenen Fußes und vor Wind geschützt. Die Sanper Wandanbau-Modelle eignen sich sowohl als lichtdurchflutete Terrassenüberdachung mit Glas als auch in der bioklimatischen Variante mit verstellbarem Lamellendach.</p>
<p>Der enorme bauliche Vorteil einer angelehnten Terrassen-Pergola besteht in der Statik: Durch die rückseitige Verankerung im Mauerwerk Ihres Wohnhauses profitiert die gesamte Anlage von der bestehenden Hausstatik. Das System, gestützt durch die zwei bis drei vorderen Aluminiumpfosten, wird extrem widerstandsfähig gegen Seitenwinde und Sturmböen. Auch sehr große Spannweiten, wie beispielsweise 7 Meter Breite und 4,5 Meter Tiefe pro Modul, lassen sich so ohne störende Mittelpfosten im Laufweg realisieren. Wer noch mehr Platz benötigt, kann die Sanper-Systeme modular und fast endlos aneinander koppeln.</p>
<p>Ein oft vergessener, aber entscheidender Punkt ist die bauphysikalische Energieeffizienz: Eine nahtlos an die Hauswand angebaute Terrassen-Pergola fungiert wie ein thermischer Puffer. Im Sommer schützt das geschlossene Dach (Dachbeschattung oder geschlossene Lamellen) die Hausfassade und die dahinterliegenden Fensterräumen vor direkter Aufheizung durch die sengende Sonne. Das Resultat: Die Wohnräume im Erdgeschoss bleiben deutlich kühler. Im Winter hingegen lassen geöffnete Lamellen die flache Sonne herein und helfen, das Haus natürlich aufzuwärmen.</p>`,
        block_2_content: `<h3>Montage an WDVS-Fassaden: Keine Kältebrücken, kein Schimmel</h3>
<p>Die Montage einer hunderte Kilogramm schweren Terrassen-Pergola aus Aluminium an eine moderne Hauswand erfordert höchste bauphysikalische Präzision. Besonders kritisch wird dies bei Häusern, die über ein Wärmedämmverbundsystem (WDVS) – also eine dicke Schicht aus Styropor oder Mineralwolle auf dem Mauerwerk – verfügen. Laien oder ungeschulte Handwerker begehen hier oft fatale Fehler, verdichten die Isolierung falsch, was später zu massiver Schimmelbildung oder Rissen in der Fassade führt.</p>
<p>Sanper löst dieses Problem durch eine extrem sichere, thermisch getrennte Montagetechnik. Wir verwenden für die Verankerung in der Hauswand modernste Hochlastanker (wie beispielsweise das Fischer Thermax System). Diese Anker überbrücken die gesamte Dämmschicht ohne Kompressionsverlust und leiten die gewaltigen Zug- und Scherkräfte der Pergola sicher in das tragende Mauerwerk oder den Beton ein. Das Wichtigste daran: Der verbaute Anti-Kälte-Konus unterbricht den Wärmefluss. Die Aluminiumstruktur der Pergola wandelt sich im Winter so nicht zu einem gigantischen Kühlkörper, der die Wärme aus dem Haus saugt. Kältebrücken und daraus resultierendes Kondenswasser (die Hauptursache für Schimmel) werden zu 100 % vermieden.</p>
<p>Ein ebenso kritischer Aspekt bei der Verwandlung der Terrasse ist die Abdichtung gegen Starkregen. Der Sanper Wandanschlussbalken wird von den hauseigenen Montageteams millimetergenau an die Fassade angepasst. Durch den präzisen Einsatz von vorkomprimierten Dichtungsbändern (Kompriband) und speziellem, UV-beständigem Fassaden-Silikon entsteht ein dauerelastischer und absolut wasserdichter Abschluss. Selbst bei starkem Schlagregen läuft kein Wasser die Hauswand hinab auf Ihre Terrasse. Das garantieren wir durch unsere strikte 100%-Eigenmontage-Regel.</p>`
    },
    "pergola-systeme/aluminium": {
        block_1_content: `<h3>Aluminium Pergola: Stranggepresste Qualität für maximale Langlebigkeit</h3>
<p>Wer nach einer dauerhaften und wartungsfreien Terrassenüberdachung sucht, landet früher oder später unweigerlich bei Aluminium. Vergessen Sie billige Bleche oder holzbasierte Dächer, die alle paar Jahre aufwändig gestrichen, lackiert und mit aggressiven Holzschutzmitteln gegen Fäulnis und Pilze behandelt werden müssen. Die Aluminium-Pergolen von Sanper bieten eine architektonisch klare, ultra-moderne Optik und erfordern genau null Wartungsaufwand – gelegentliches feuchtes Abwischen genügt völlig, um die Anlage selbst nach einem Jahrzehnt wie neu aussehen zu lassen.</p>
<p>Das Geheimnis unserer extremen Konstruktionsfestigkeit liegt im gewählten Material. Wir nutzen hochentwickeltes, stranggepresstes Aluminium (Legierung EN AW-6060 / AlMgSi0,5). Diese spezielle Legierung aus dem Fenster- und Fassadenbau bietet die absolut perfekte Balance zwischen geringem Eigengewicht und enormer struktureller Festigkeit. Während viele Discount-Dächer im Internet mit gefährlich dünnen Profilwandstärken von rund 1.4 mm arbeiten, verbaut Sanper bei den tragenden Pfosten und Rahmenkonstruktionen massive Materialstärken zwischen 3 und 5 Millimetern. Das sichert eine statische Tragfähigkeit, die selbst bei Hurrikan-ähnlichen Stürmen und hohen Schneelasten nicht nachgibt.</p>
<p>Ein oft unterschätzter Qualitätsunterschied ist die Verbindungstechnik. Wenn eine Konstruktion außen rostet, dann startet es an den Schrauben und Gelenken. Daher lässt Sanper hier keine Kompromisse zu. Wir verbauen ausschließlich hochfeste, völlig unsichtbare Edelstahlbolzen für die Tragwerkverbindungen sowie selbstschmierende Messinglager für alle sich bewegenden Teile (wie bei unserem Lamellendach). Das Resultat ist eine geräuschlose, sanfte Bedienbarkeit über Jahrzehnte hinweg, völlig egal ob bei -20°C im tiefsten Winter oder bei 40°C in der Sommerhitze.</p>`,
        block_2_content: `<h3>Qualicoat-Pulverbeschichtung und Zukunftssicherheit für den Wintergarten</h3>
<p>Eine Pergola steht das gesamte Jahr über im Freien und ist unbarmherziger UV-Strahlung, Regen, saurem Smog, Frost und Hagel ausgesetzt. Bei minderwertigen Systemen kreidet hier schnell der Lack aus oder löst sich gar ab. Um dies zu verhindern, erhalten alle Sanper Aluminium-Systeme ein industrielles Oberflächen-Finish durch hochresistente Pulverbeschichtungen, die den harten europäischen Qualicoat-Zertifizierungsstandards entsprechen. Dies garantiert nicht nur enorme Kratz- und Abriebfestigkeit, sondern auch dauerhafte Farbechtheit.</p>
<p>Dank dieser Pulverbeschichtung steht Ihnen die gesamte RAL-Farbpalette mit über 200 zur Verfügung. Egal ob sie ein hochmodernes Anthrazit (DB 703, RAL 7016) mit leichtem Glimmer-Effekt, ein strahlendes Weiß oder eine Sonderlackierung passend zu den Fensterrahmen Ihres Traumhauses wünschen – Sanper sorgt für eine 100%ige Farbintegration in die bestehende Architektur. Die seidenmatte oder feinstrukturierte Verarbeitung absorbiert Lichtbrechungen und verleiht der Pergola den echten Vibe eines Premium-Bauteils.</p>
<p>Ein gigantischer Vorteil der Sanper-Aluminium-Philosophie ist die Modularität für die Zukunft. Viele Kunden möchten erst nur ein Dach, entscheiden sich aber nach 2 oder 3 Jahren dazu, aus der offenen Pergola einen windgeschützten Kaltwintergarten oder ein verglastes Gartenzimmer zu machen. Bei Billigprodukten macht die Statik hier einen Strich durch die Rechnung. Das Gewicht von drei schweren Front-Glasschiebewänden aus 10mm starkem ESG (Einscheiben-Sicherheitsglas) würde die Anlage zum Einsturz bringen. Nicht so bei Sanper: Unsere Profile sind von vornherein massiv überdimensioniert, um spätere Wind-, Glas- und Zusatzlasten sicher über die Rahmenkonstruktion und die Pfosten in das Fundament abzuleiten. Jeder Wandel bleibt modular jederzeit einfach möglich.</p>`
    },
    "pergola-systeme/freistehend": {
        block_1_content: `<h3>Die freistehende Pergola: Design-Fokus für Garten und Pool</h3>
<p>Nicht jede Terrasse ist direkt am Haus, und nicht jede Hausfassade (starke Verschachtelungen, alte Bausubstanz, Extremdämmung) eignet sich zwingend für eine tonnenschwere Wandmontage. Genau dort spielt eine freistehende Pergola ihre absoluten Vorteile aus. Sie löst sich komplett von der bestehenden Gebäudehülle und wird zu einer eigenständigen architektonischen Oase mitten in Ihrem Garten, am Rande der Terrasse oder als absolut luxuriöses Poolhaus.</p>
<p>Auf vier massiven Aluminiumpfosten gestützt, kann eine freistehende Pergola von Sanper überall aufgestellt werden. Besonders beliebt sind diese Systeme in Kombination mit 120° drehbaren Lamellen. Sie verwandeln eine freie Wiese oder die freie Poolfläche auf Knopfdruck in einen wind-, sicht- und regengeschützten Raum. Keine Hauswand schluckt Licht, der Kühleffekt des Windes kann im Sommer von allen vier Seiten zur Belüftung genutzt werden. Sobald es ungemütlich wird – vielleicht durch aufziehende Frühlingsgewitter – schließen die Motoren das Dach, und die Party geht draußen einfach weiter.</p>
<p>Da die Systeme völlig autark agieren, spielt das intelligente Entwässerungssystem von Sanper hier eine besonders große Rolle. Das Regenwasser, welches bei geschlossenen Anlagen gesammelt wird, läuft nicht wild an den Kanten hinab, wo es Ihre Möbel oder Begrünung wegschwemmen würde. Eine unsichtbare Rinne im Dachprofil fängt die Wassermengen auf und leitet sie hochkontrolliert direkt durch das Innere der wuchtigen Aluminium-Pfosten hinab auf den Boden oder direkt in die Garten-Drainage ein. Eine 100 % saubere Lösung, die das ultra-minimalistische Bauhaus-Design nicht durch aufgepflanschte Fallrohre verschandelt.</p>`,
        block_2_content: `<h3>Extrem-Statik und Punktfundamente für freistehende Systeme</h3>
<p>Eine wichtige physikalische Tatsache darf bei freistehenden Überdachungen nicht ignoriert werden: Weil sie nicht an einem schweren, massiven Wohnhaus anliegen, sind sie Winden, Sog und Druck von allen vier Seiten ungeschoren ausgesetzt. Ein freistehendes Dach wirkt bei einem Sturm durch die Verwirbelungen unterhalb der Lamellen oder des Glases wie ein riesiger Drachen oder Flügel. Es erfordert enorm starkes Engineering, um ein Abheben oder Verwinden der Konstruktion zu verhindern.</p>
<p>Sanper fertigt die Rahmenkonstruktionen seiner freistehenden Pergolen aus 3-5mm starkem, stranggepresstem Aluminium. Dieses bildet einen statisch extrem stabilen Käfig, welcher die auftretenden Zug- und Scherkräfte perfekt in die vier Vertikalstützen überträgt. Unsere Systeme sind zertifiziert, um Orkanböen bis zu enormen 140 km/h sowie sehr hohen winterlichen Schneelasten problemlos standzuhalten. Wir setzen dabei ausschließlich auf unsichtbar eingepasste Edelstahlklammern und Bolzen in den Eckknoten der Anlage, wodurch ein "Wackeln" völlig ausgeschlossen ist.</p>
<p>Da das stärkste Aluminiumprofil nichts bringt, wenn es einfach umfällt, ist die Bodenverankerung bei einer freistehenden Konstruktion der kritischste Aspekt. Anders als oft bei Baumarkt-Produkten, die Kunden auf bloße Terrassenfliesen dübeln, koordiniert das Sanper-Montageteam die Anlage mit hochsicheren Beton-Punktfundamenten (z.B. 80 cm tief, frostfrei gegründet). Die massiven Fußplatten der Pfosten werden darin mit Schwerlastankern verschraubt, unsichtbar verkleidet und bilden eine Verbindung für die Ewigkeit. Durch unsere eigene, haftende und fachgerechte Werksmontage vermeiden Sie gefährliche Sturmschäden durch DIY-Montage-Pfuscher.</p>`
    },
    "pergola-systeme/preise": {
        block_1_content: `<h3>Pergola Kosten: Qualität erkennen und Zwischenhändler ausschalten</h3>
<p>Wenn es um Pergola Preise geht, öffnet der Markt eine irrsinnige Spanne: Vom wackeligen Internet-Bausatz für 2.000 € bis zur High-End-Designer-Lösung für 30.000 €. Wer sich über die tatsächlichen Kosten einer bioklimatischen Lamellendach-Pergola oder eines Glas-Wintergartens informiert, muss wissen, wofür er eigentlich zahlt. Das teuerste an hochwertigen Überdachungen sind oft gar nicht das Aluminium oder die Somfy-Motoren – es sind die Margen von zwei oder drei Zwischenhändlern, Subunternehmern und Import-Resellern, die den Preis künstlich aufblähen.</p>
<p>Sanper ist den Markt genau an diesem Punkt strategisch anders angegangen. Durch unser konsequentes Direkt-vom-Hersteller-Prinzip umgehen wir alle Handelskalkulationen. Sie kaufen Ihr neues Lamellendach oder Ihren Kaltwintergarten unmittelbar von den Ingenieuren und Fabrikanten, die es produzieren. Bei absolut identischer Premium-Legierung, vergleichbarer Wandstärke (3-5 mm starkes EN AW-6060 Alu) und gleicher Technik verbuchen Kunden einen massiven Preisvorteil gegenüber marktgängigen Mitbewerbern. Sie erhalten echtes High-End für den Preis der gehobenen Mittelklasse.</p>
<p>Entscheidend für lange Freude sind auch die oft unsichtbaren Qualitätsfaktoren, die den wahren Wert beeinflussen: Handelt es sich beim Lack um eine kratzfeste Qualicoat-Pulverbeschichtung? Setzt die Konstruktion auf Edelstahlbolzen und selbstschmierende, lebenslang wartungsfreie Messinglager? Wie laut und anfällig für Rost sind verschleißende Plastiklager bei Discount-Geräten? Wer bereit ist, zu vergleichen, muss neben dem bloßen Preisetikett zwingend die physikalische Robustheit der Rahmenkonstruktion und die verbauten Elektronikkomponenten erfragen.</p>`,
        block_2_content: `<h3>5 Jahre Garantie und Eigene Montage ohne Risiko-Sub-Unternehmer</h3>
<p>Das größte finanzielle Risiko beim Kauf einer Pergola im Netz sind versteckte Montagekosten und unklare Gewährleistungen. Viele Händler sind nur Logistikverteiler: Die Paletten werden per Spedition an die Bordsteinkante gekippt, danach müssen Sie selbst lokale Handwerker suchen und bezahlen. Kommt es zu Fehlbohrungen am Haus, Schimmel durch ignorierte Kältebrücken an der WDVS-Fassade (Wärmedämmung) oder regnet es durch Spalten zwischen Wandbalken und Ziegelwand, schieben sich Händler und Handwerker die Schuld gegenseitig zu.</p>
<p>Sanper eliminiert dieses Ping-Pong-Spiel der Verantwortung ausnahmslos. Unsere Preise sind hochtransparente Komplettlösungen für Kunden in NRW und Umgebung. Bei uns wird jede maßgefertigte Produktion zwingend und ausschließlich von hauseigenen, TÜV-ausgebildeten Sanper-Montageteams bei Ihnen im Garten aufgebaut und zertifiziert abgenommen. Es kommen thermisch getrennte Ankersysteme (Fischer Thermax) für dicke Fassadendämmungen, sowie Hightech-Kompribänder und Fassadensilikon gegen Feuchtigkeitseinbruch zum Facharbeitereinsatz.</p>
<p>Durch die Montage aus einer Hand – ohne windige Sub-Unternehmer – garantieren wir nicht nur absolute Bau-Sicherheit für Ihr Grundstück, sondern übernehmen 100 % Verantwortung. Dies besiegeln wir mit einer echten, wasserdichten 5 Jahres-Garantie auf das Lamellendach sowie eine lebenslange Teileverfügbarkeits-Garantie für Motoren und Gelenke. Vergleichen Sie niemals nur den reinen Modulpreis, sondern fordern Sie für die Ermittlung der echten Kosten immer ein Angebot mit Lieferung, Montagematerial, Profi-Arbeitszeit und Abnahme an – bei Sanper ist das im Rundum-Sorglos-Plan Standard.</p>`
    },
    "wintergarten-systeme/glasschiebewand": {
        block_1_content: `<h3>Komfortable Glasschiebewände: Winddicht ohne Rahmen-Verlust</h3>
<p>Eine Terrassenüberdachung bietet Schutz vor Regen – aber erst die Verglasung der Seitenwände verwandelt den Platz in ein 360-Grad nutzbares Gartenzimmer. Sanper Glasschiebewände sind das absolute Nonplusultra für diesen Kaltwintergarten-Ausbau. Sie bestehen aus massiven Scheiben aus Einscheiben-Sicherheitsglas (ESG) und verzichten je nach Systemwahl komplett auf eine störende vertikale Rahmenführung aus Aluminium. Dieses rahmenlose Design verschafft Ihnen bei geschlossenen Scheiben eine uneingeschränkte, 100 % ungestörte Panoramaaussicht auf Ihren geliebten Garten, sperrt aber kalte Zugluft rabiat aus.</p>
<p>Die Schiebeelemente gleiten nahezu widerstandslos und geräuschlos auf teflonbeschichteten Mehrspur-Laufschienen (von 2 bis 5 Spuren) hin und her. Ein clever konzipiertes Mitnehmersystem sorgt dafür, dass sich beim Ziehen der vordersten Scheibe alle darauffolgenden Gläser automatisch ineinanderschieben, um eine geschlossene Front zu generieren. Durch feine seitliche und untere EPDM-Gummilippen sowie unsichtbare Bürstendichtungen schließen die Elemente so pressfest, dass Wind, kalte Herbstbrisen und starker Schlagregen einfach draußen bleiben und die Terrasse extrem zügig durch Infrarotstrahler gewärmt werden kann.</p>
<p>Die Dimensionen, die dabei sicher realisiert werden können, sind enorm. Typischerweise kommen Glasscheiben mit Materialstärken von 8 mm (Gewicht 20,0 kg/m²) oder sogar 10 mm (Gewicht 25,0 kg/m²) zum Einsatz. Das Glas wird bei der industriellen Herstellung auf über 500 °C erhitzt und schlagartig heruntergekühlt. Die sich daraus ergebenden molekularen Zug- und Druckspannungen machen das Sanper ESG unfassbar resistent gegen Stöße (ein abirrender Fußball oder extremer Hagel sind kein Problemkreislauf). Sollte es im absoluten Extremfall jemals brechen, zerbröselt das Glas komplett stumpfkantig und verletzungssicher zu hunderten kleinen Würfeln, statt in messerscharfen, tödlichen Scherben – ein riesiger Sicherheitsgewinn für Familien mit Kindern.</p>`,
        block_2_content: `<h3>Nachrüstbarkeit und das absolute High-End: Giyotin-Systeme</h3>
<p>Einer der stärksten Pluspunkte in der Sanper-Planung ist die unbegrenzte Modularität. Ein Großteil unserer zufriedenen Kunden startet zunächst mit einer Sanper Pergola oder einer seitlich offenen Lamellen-Anlage. Da unsere stranggepressten Aluminium-Basisprofile über eine extra dicke Wandstärke von 3-5mm (bei stark dimensioniertem EN AW-6060 Material) und extreme statische Kapazitäten verfügen, lassen sich unsere schweren Glasschiebesysteme meist auch nach Jahren, völlig stressfrei bis auf dem Millimeter nachrüsten. Das Glasgewicht von mehreren hunderten Kilo wird millimetergenau in das Fundament abgetragen, ohne dass sich das Dach auch nur einen Bruchteil biegt.</p>
<p>Wer auf Innovation und maximalen Aha-Effekt setzt, entscheidet sich neben seitlichen Schiebe-Türen für die Giyotin-Verglasung in der Front. Im Gegensatz zum horizontalen System (links/rechts öffnen), funktioniert das Guillotine-Prinzip motorisiert vertikal! Aus der offenen Terrasse schließt sich die Brüstungsverglasung lautlos per Knopfdruck wie eine Wand von oben nach unten. Die Anlage besteht aus 2 oder 3 Glaselementen. Das starre Bodenelement dient zeitgleich bei geöffneter Wand als sichere Front-Brüstung nach draußen. </p>
<p>Gesteuert über eine Funkfernbedienung greifen hier unsichtbare, extrem hochbelastbare Edelstahlketten oder Zahnriemen ein, die tief im schlanken Aluminiumrahmen (Einbautiefe nur 100 bis 158 mm) sitzen und Ausgleichgewichte verschieben. Selbst Glaselemente mit Lasten von fast 500 kg gleiten durch dieses System absolut ruckelfrei hoch in die Dichtpositionen. Sie kontrollieren den Luftstrom perfekt – schließen Sie die Glas-Giyotine zur Hälfte, können Zigarettenqualm oder Hitze wunderbar über Kopf abziehen, während sitzende Gäste vom unteren Element vor kaltem Bodenwind geschützt bleiben. </p>`
    },
    "zip-screen-systeme/senkrechtmarkise": {
        block_1_content: `<h3>Technologie trifft Hitzeschutz: Der ZIP-Screen erklärt</h3>
<p>Eine moderne Terrassenüberdachung, Pergola oder große Schiebefensterfront bringt enorm viel Licht in das Haus. Sobald jedoch die hochsommerliche Mittagssonne tief steht oder der Westwind Abends feucht um die Ecke fegt, braucht man einen physikalischen Schild. Hier entfaltet eine ZIP-Senkrechtmarkise ihre unschlagbare Superkraft. Sie agiert komplett anders als alte, flatternde Gelenkarm-Markisen oder Baumarkt-Netze.</p>
<p>Ein herkömmliches Außenrollo wird an den Seiten nicht geführt, es baumelt an einer schweren Fallleiste gen Erdboden. Kommt Wind auf, knallt das Tuch lautstark gegen die Fensterscheiben – ein Graus für jeden Eigenheimbesitzer. Ein Sanper ZIP-Screen nutzt hierfür die geniale z-LOCK™-Technologie, bei der ein hochfester Halbreißverschluss komplett nahtlos, mittels Hitze oder Nähten vertikal entlang der seitlichen Tuchkanten angeschweißt wird. Dieser "Reißverschluss" fährt lückenlos in den schlanken, zweigeteilten Aluminium-Seitenführungsschienen.</p>
<p>Innerhalb der Führungsschienen liegt der zweite Geniestreich: Der Keder ist "schwimmend" auf Kunststoffpuffern gelagert. Wenn der Wind stark in das ca. 6 Meter hohe Stoff-Segel drückt, reißt das System nicht an den Nähten ab, sondern die Kunststoffschiene gibt mikroskopisch nach und verteilt die extreme Windlast absorptionsfähig auf die gesamte Länge der Schienen (statt wie bei normalen Markisen nur auf 3 Fixpunkte). Das System wird straff wie ein Trampolin. Das Ergebnis: Die Sanper ZIP-Senkrechtmarkise erreicht in Sturmkasten-Tests locker Windwiderstandsklasse 6. Orkanartige Windbelastungen bis zu unfassbaren 120 km/h hält die Markise ausgefahren stand, ohne Falten zu schlagen.</p>`,
        block_2_content: `<h3>Sonnenschutz mit Aussicht: Der g_tot Wert und die Privatsphäre</h3>
<p>Die Effizienz gegen Hitzestau in Räumen ist bei vertikalen Screens absolut beispiellos und physikalisch weitaus stärker als bei teuren, verdunkelnden Plissees, die logischerweise von der falschen, der warmen Seite an die Fensterscheibe geklebt werden. Unsere Screen-Gewebe, etwa hochverdichtetes PVC/Polyester aus der legendären Soltis-Reihe, fangen die solare Sonnenenergie ab, noch ehe sie auf das Fensterglas der Terrasse knallt und in den Raum eintreten kann.</p>
<p>Das clevere Mesh-Gewebe nutzt eine Mischung aus Absorption, Reflexion und Transmission, die dazu führt, dass unfassbare 97 % der eindringenden hochsommerlichen Wärmeenergie von der Fassade abgeblockt werden. Durch den winzigen, physikalisch relevanten Gesamtenergiedurchlassgrad (den sogenannten g_tot-Wert von z.B. 0,05-0,12) ersparen ZIP-Screens im Dauerbetrieb bei Südausrichtungen im Juli und August förmlich eine stromfressende Klimaanlage für den Wintergarten.</p>
<p>Doch das Tuch ist nicht nur ein Energiesparweltmeister, sondern schützt exzellent die Privatsphäre (Sichtschutz) ohne "Keller-Feeling". Durch die präzise Mikroperforation des Stoffes mit einem Öffnungsfaktor (OF) von branchenweiten, optimalen 3 bis 5 Prozent entsteht das Phänomen der Leuchtdichten-Differenzierung. Tagsüber können Sie aus Ihrem leicht gedimmten Zimmer oder dem Halbschatten der Pergola kristallklar wie durch eine Sonnenbrille in den Garten und in die Natur filtern. Dunkle Stoffe (etwa Anthrazit) verhindern dabei lästige Blendeffekte fast vollständig. Für den vorbeigebenden Nachbarn kehrt sich dieser Effekt völlig um: Sie sehen durch die Maschen lediglich das Reflexionsbild des Himmels und keine Chance, durch die dunklen Maschen in Ihren gut geschützten Wintergarten oder auf Sie beim Sonntagsfrühstücken zu schauen.</p>`
    },
    "zip-screen-systeme/terrasse": {
        block_1_content: `<h3>Der perfekte Wind- und Sichtschutz für jede Terrasse</h3>
<p>Eine offene Terrasse bietet den Traum vom Leben an der frischen Luft. Doch in Deutschland zeigt der Wind spätestens zur Cocktail-Stunde im Spätsommer, dass ein vollkommen offener Seitenbereich extrem ungemütlich wird. Mit seitlichen ZIP-Screens von Sanper verschließen Sie Ihre Lamellendach-Pergola, das Aluminium-Terrassendach oder sogar offene Balkone in Sekunden. Was offen wirkte, wird per Fernbedienung motorisiert, ultra-leise zu einer witterungsgeschützten Lounge.</p>
<p>Technologisch sind diese Systeme auf maximale Dauerlaufleistung designt. Während gewöhnliche Stoffmarkisen im Wind flattern oder im Kasten verkanten, gleitet das High-Tech Tuch der Sanper Screens auf Grund des fest verschweißten Keder-Reißverschlusses an den Seitenrändern perfekt gespannt durch die aus einem Block gefrästen, ultra-schlanken Aluminium-Kassettenschienen nach unten. Diese z-LOCK™-Technologie eliminiert lästige Gerassel und nervige Stoffwellen, die man von günstigen Seitenrollos der Baumarkt-Liga kennt, komplett.</p>
<p>Da die Tuchflächen der Screens lücken- und spaltfrei bis exakt an die Führungsschiene sowie die untere, gummierte Fall-Leiste auf den Boden abschließen, bieten Sanper Markisen abseits des reinen Hitzeschutzes einen genialen, mechanischen Insektenschutz. Wespenköniginnen, die im Hochsommer den Apfelkuchen heimsuchen wollen, oder Milliarden hungriger Mücken im Spätsommer haben nicht den winzigsten Durchschlupf – während die mikroperforierte Netzstruktur des Stoffes noch immer stetig feine, angenehme Frischluft durchziehen lässt und das Ersticken durch stehende Hitze vollends unterbindet.</p>`,
        block_2_content: `<h3>Langlebigkeit, Nachrüstung und extrem smarte Technik</h3>
<p>Oft fragt man sich: Sollte ich gleich beim Kauf einer Sanper Pergola oder eines Gartenzimmers alle vier Seiten mit Senkrechtmarkisen bestücken? Wenn es das Budget zum Start der Gartensaison nicht hergibt, ist das überhaupt kein Problem. Die durchdachten Aluminium-Architekturen unserer Dächer besitzen in den massiven 3-5mm starken Rahmenprofilen bereits dedizierte Nuten und Einschiebemöglichkeiten. Ein späteres Nachrüsten der wuchtigen ZIP-Screen-Kassettenkästen kann von unseren Sanper Profi-Monteuren auf den Millimeter passgenau und völlig schnittfrei vorgenommen werden. Es entstehen keine hässlichen Bohrlöcher quer durch die Hauptpfeiler.</p>
<p>Für die Steuerung auf der Terrasse setzt Sanper kompromisslos auf Hightech. Keiner kurbelt mehr per Hand. Die Systeme sind mit absolut laufruhigen, völlig wartungsfreien Röhrenmotoren der Branchenführer (wie Somfy) ausgestattet. Über das Funkprotokoll integrieren sich diese Rollos auch nahtlos in Smart-Home Controller. Wer absolut proaktiv arbeiten will, lässt das System über eine Tahoma-Switch steuern und montiert außen an Hausfassade kleine Licht- und Windsensoren.</p>
<p>Wie intelligent das läuft, zeigt der Herbst: Zieht überraschend am Nachmittag eine peitschende und sturmartige Gewitter-Böenfront auf und Sie sitzen gerade ungeahnt auf Arbeit fest, registriert der Windsensor draußen am Sanper Dach die Sturmböen. Ab einem Grenzwert (die Sanper-Screens halten bis Orkanstärke von 120 km/h (Windklasse 6) allem absolut Stand, auch wenn der Wind mit 400 Newtonmeter pro Quadratmeter aufprallt) geben die Sensoren ein Sicherheitsprotokoll aus: Alle offenen ZIP-Screens auf der Terrasse schließen automatisch voll herab. Alles Habgut dahinter ist sofort vor dem Gewitter- und Schlagregen gerettet. Absolute Seelenruhe und Komfortsteigerung!</p>`
    },
    "zip-screen-systeme/wetterfest": {
        block_1_content: `<h3>Wetterfeste Außenrollos: Der robuste Schutzpanzer vor dem Fenster</h3>
<p>Das Konzept des klassischen "Sonnenschirme" hat bei Sanper schon extrem lange ausgedient. Unsere Kunden aus ganz NRW rüsten ihre Terrassendächer, Wintergärten aber oftmals auch riesige, offene Wohnzimmer-Panoramascheiben in die Himmelsrichtung Süd oder Süd-West mit hochfunktionalen ZIP-Screens aus. Der Grund dafür ist die absolute Unverträglichkeit von reinen Stoffmarkisen mit den harten Herbststürmen oder Frühlingsgewittern. Wo andere Anlagen wegen Zerreißen und "Segelflug"-Risiko umständlich vom Menschen eingerollt werden, machen Sanper wetterfeste Außenrollos komplett zu und bilden den perfekten Schutzpanzer in der Windlast-Spitze.</p>
<p>Wie hält reines Gewebe dem Druck eines Orkantiefs fern? Das Geheimnis steckt in der Reißverschluss-Technik (Keder), die am Seitenrand des Tuches unlösbar thermisch angeschweißt ist. Statt punktuell am Rand eine schwache Aluschiene anzubringen, in die das Netz "geschoben" wird, klemmt das z-LOCK™-Reißverschlusssystem extrem sicher in der zweigeteilten Laufkammer der wuchtigen Aluminium-Säulen. Im Falle eines frontalen Windstoßes zieht die Spannung das Tuch in alle Richtungen. Diese gigantischen Gewichte geben nun dank der stoßsicheren, schwimmenden Lagerpuffer-Federung (einem Kunststoff-Inlay im Keder der Seitenschiene) wenige kritische Millimeter nach, wodurch ein Reißen unmöglich wird. So absorbiert der Screen dynamisch die Angriffe von 120 km/h schnellen Stürmen.</p>
<p>Und hier zahlt sich auch die Premium-Wahl des Tuchgewebes aus (etwa vorgespanntes Soltis Polyester mit Flüssig-PVC ummantelt). Es reißt nicht ab, verbiegt nicht stark und franst nicht stumpf an den Rändern der Kassette aus, zudem ist es beständig gegen Schimmel oder das Ansetzen von Grünspan, falls es im feuchten und komplett durchnässten Herbst einmal eingefahren werden musste.</p>`,
        block_2_content: `<h3>Klimaanlagen-Fresser und maximale Flexibilität im Smart Home</h3>
<p>Die größte Investitionsberechtigung eines komplett wetterfesten vertikalen Zip-Screens liegt oftmals in der Amortisierung von enormen Stromkosten innerhalb des Hauses anstatt "nur" dem optischen Tuning der neuen Pergola am Pooldeck. Glas verhält sich wie ein massiver Brennglas-Spiegel. Treffen hochsommerliche UV-Strahlen im August stundenlang mit 45 Grad Einfallswinkel auf offene Architektur, erzeugt dies brutalen Hitzestau in der Etage dahinter.</p>
<p>Innenraum-Plissees kämpfen hier einen vollends verheerenden, nutzlosen Isolations-Krieg. Die Hitze hat zu diesem Moment das Glas bereits durchschritten. Der Sanper Screen setzt daher als absolute Hitze-Phalanx außen an, wo er durch die dunkle Pigment-Webstruktur (z.B. Anthrazit) 97% der Solarhitze schluckt und ungenutzt per Reflexion oder direkter UV-Absorption abführt. Der resultierende, geringe g_tot Wert (teilweise bis zu mikroskopischen 0,05) hält das dahinterliegende Terrassenzimmer fast 100% autark im Schatten. Klimaanlagen im Erdgeschoss und Split-Geräte können sofort runtergeregelt oder meist sogar komplett aus dem Jahres-Planer gestrichen werden, was direkt bares Geld in Form von KW/h Stromkosten spart.</p>
<p>Natürlich müssen diese komplexen Klimaziele im Haus und an der Terrasse bedienbar sein, ohne ständig im Kopf die Wetter-App des Handys am Laufen zu haben. Deshalb verzichten diese massiven Anlagen aus Prinzip gänzlich auf manuelle Drehkurbeln oder reißende Seilzüge. Die eingebauten SOMFY-Wellenmotoren laufen hermetisch kapseliert auf Knopfdruck der Fernbedienung über Funk. Sind Sie auf Reisen in Südspanien, während Zuhause in NRW das 30-Grad-Wochenende abbrennt, registrieren integrierte Lux-Messer (Sonnensensoren) an der Kassette die UV-Spitzenlast – und alle Haus-Rollos rattern flüsterleise von ganz alleine hinab, um das Haus gegen das abendliche Saunagefühl extrem zuverlässig abzukühlen.</p>`
    }
};

let modified = false;

data.forEach(page => {
    const override = updates[page.slug];
    if (override) {
        page.block_1_content = override.block_1_content;
        page.block_2_content = override.block_2_content;
        modified = true;
    }
});

if (modified) {
    fs.writeFileSync(jsonPath, JSON.stringify(data, null, 4), 'utf8');
    console.log('✅ successfully patched landing_pages.json with deep NotebookLM content!');
} else {
    console.log('❌ no slugs matched or nothing was updated.');
}
