// merge_csv_content.cjs
// Merges CSV content blocks into landing_pages.json

const fs = require('fs');
const path = require('path');

// CSV data parsed from the provided input
const csvData = [
    { slug: "", block_1_content: "Sanper ist kein Anbieter für Standardlösungen. Wir arbeiten für Menschen, die ihren Außenbereich langfristig nutzen wollen und deshalb mehr brauchen als ein Produkt von der Stange. Der entscheidende Unterschied liegt in der Verantwortung: Planung, Fertigung und Montage müssen zusammenpassen. Bei Sanper sind Maße, Statik, Material und Befestigung vorab abgestimmt – nicht erst auf der Baustelle. Diese Seite hilft Ihnen zu prüfen, ob ein individuell geplantes System für Ihr Projekt sinnvoll ist, bevor Sie Angebote vergleichen.", block_2_content: "Viele Probleme entstehen nach dem Kauf: unklare Zuständigkeiten, Verzögerungen, fehlende Ersatzteile oder Monteure ohne Systemkenntnis. Diese Risiken sind bei Outdoor-Systemen besonders relevant. Sanper reduziert sie durch klare Verantwortlichkeit, abgestimmte Prozesse und planbaren Service. Wenn Sie eine kurzfristige Lösung suchen, gibt es einfachere Wege. Wenn Sie Wert auf Haltbarkeit und Sicherheit legen, sind Sie hier richtig.", block_1_placement: "after_intro", block_2_placement: "before_trust", cta_primary_text: "Beratung starten", cta_secondary_text: "Kostenloses Angebot", faq_theme: "allgemein", faq_unique_q_count: 5 },
    { slug: "pergola-systeme", block_1_content: "Ein Pergola-System ist keine Einzelanschaffung, sondern eine Entscheidung über Nutzung, Erweiterbarkeit und Lebensdauer. Entscheidend ist, ob Dach, Entwässerung, Beschattung und Steuerung als Einheit gedacht sind. Systeme, die von Anfang an modular geplant werden, lassen sich an neue Anforderungen anpassen, ohne neu bauen zu müssen. Diese Seite hilft zu klären, ob ein durchgängiges System für Ihre Nutzung sinnvoller ist als eine einzelne Lösung.", block_2_content: "Risiken entstehen, wenn Komponenten nicht zusammenpassen: spätere Nachrüstungen, Undichtigkeiten oder eingeschränkte Erweiterungen. Wer das Systemdenken ignoriert, zahlt langfristig doppelt. Eine frühe Systementscheidung verhindert diese Folgekosten.", block_1_placement: "after_intro", block_2_placement: "before_faq", cta_primary_text: "System prüfen", cta_secondary_text: "—", faq_theme: "system", faq_unique_q_count: 5 },
    { slug: "pergola-systeme/bioklimatisch", block_1_content: "Bioklimatische Systeme sind sinnvoll, wenn Hitze, Luftstau und wechselnde Wetterbedingungen die Nutzung einschränken. Die verstellbaren Lamellen regulieren Licht und Luft aktiv und schaffen ein nutzbares Mikroklima. Diese Lösung ist nicht für reine Beschattung gedacht, sondern für Flächen, die regelmäßig genutzt werden.", block_2_content: "Risiken entstehen durch falsche Erwartungen an Steuerung und Automatik. Ohne korrekte Auslegung kann Hitze bleiben oder Regen nicht sauber abgeführt werden.", block_1_placement: "after_intro", block_2_placement: "before_faq", cta_primary_text: "Beratung prüfen", cta_secondary_text: "—", faq_theme: "klima", faq_unique_q_count: 5 },
    { slug: "pergola-systeme/lamellendach", block_1_content: "Ein Lamellendach bietet Kontrolle über Licht, Luft und Regen. Im Vergleich zu Glas oder Stoff steht hier die flexible Nutzung im Vordergrund. Diese Seite hilft, die Lösung anhand des tatsächlichen Nutzungsverhaltens zu bewerten – nicht anhand von Optik allein.", block_2_content: "Grenzen bestehen bei maximaler Lichtdurchlässigkeit oder vollständiger Abdichtung. Wer Wintergarten-Eigenschaften erwartet, wählt die falsche Lösung.", block_1_placement: "after_features", block_2_placement: "before_faq", cta_primary_text: "Lösung vergleichen", cta_secondary_text: "—", faq_theme: "vergleich", faq_unique_q_count: 5 },
    { slug: "pergola-systeme/aluminium", block_1_content: "Aluminium eignet sich für Systeme, die formstabil, wartungsarm und langlebig sein sollen. Im Vergleich zu Holz oder Stahl verändert es sich kaum und benötigt keine regelmäßige Pflege. Diese Seite hilft bei der Materialentscheidung anhand von Nutzung und Wartungsaufwand.", block_2_content: "Risiken liegen in falschen Materialstärken oder minderwertigen Profilen. Nicht jedes Aluminium erfüllt die gleichen Anforderungen.", block_1_placement: "after_intro", block_2_placement: "before_faq", cta_primary_text: "Material bewerten", cta_secondary_text: "—", faq_theme: "material", faq_unique_q_count: 5 },
    { slug: "pergola-systeme/freistehend", block_1_content: "Freistehende Pergolen ermöglichen maximale Freiheit bei der Platzierung, etwa bei Pool- oder Gartenbereichen. Voraussetzung ist eine saubere statische Planung. Diese Seite hilft zu klären, wann freistehend technisch sinnvoll ist.", block_2_content: "Häufige Risiken sind fehlende Fundamente oder unterschätzte Windlasten. Ohne Prüfung drohen spätere Schäden oder Genehmigungsprobleme.", block_1_placement: "after_intro", block_2_placement: "before_cta", cta_primary_text: "Machbarkeit klären", cta_secondary_text: "—", faq_theme: "statik", faq_unique_q_count: 5 },
    { slug: "pergola-systeme/terrasse", block_1_content: "Terrassenlösungen müssen an Gebäudeanschlüsse, Gefälle und Abdichtung angepasst werden. Diese Seite hilft zu prüfen, wie eine Pergola sinnvoll an das Haus angebunden wird, ohne Bausubstanz zu gefährden.", block_2_content: "Risiken entstehen durch falsche Befestigung oder mangelhafte Abdichtung. Das zeigt sich oft erst nach Monaten.", block_1_placement: "after_intro", block_2_placement: "before_faq", cta_primary_text: "Beratung anfragen", cta_secondary_text: "—", faq_theme: "anbau", faq_unique_q_count: 5 },
    { slug: "pergola-systeme/wintergarten-kombination", block_1_content: "Die Kombination aus Pergola und Glas kann sinnvoll sein, wenn flexible Nutzung gewünscht ist. Entscheidend ist die klare Abgrenzung zwischen offenem und geschlossenem Bereich.", block_2_content: "Risiken liegen in Kondensatbildung und falscher Belüftung, wenn Nutzung und Konstruktion nicht zusammenpassen.", block_1_placement: "after_intro", block_2_placement: "before_faq", cta_primary_text: "Projekt prüfen", cta_secondary_text: "—", faq_theme: "hybrid", faq_unique_q_count: 5 },
    { slug: "pergola-systeme/montage", block_1_content: "Eine saubere Montage entscheidet über Funktion und Lebensdauer. Diese Seite erklärt den Ablauf von Vorbereitung bis Einweisung und schafft Transparenz über Dauer und Koordination.", block_2_content: "Risiken entstehen durch Fremdmonteure oder fehlende Systemkenntnis. Das führt zu Nacharbeiten und Verzögerungen.", block_1_placement: "after_intro", block_2_placement: "before_cta", cta_primary_text: "Ablauf klären", cta_secondary_text: "—", faq_theme: "montage", faq_unique_q_count: 5 },
    { slug: "pergola-systeme/preise", block_1_content: "Preise ergeben sich aus Maßen, Technik, Montage und Zubehör. Diese Seite erklärt, welche Faktoren den Preis beeinflussen, damit Angebote vergleichbar werden.", block_2_content: "Risiken bestehen bei Pauschalpreisen ohne Leistungsabgrenzung. Nachträge sind dann vorprogrammiert.", block_1_placement: "after_intro", block_2_placement: "before_cta", cta_primary_text: "Angebot anfordern", cta_secondary_text: "—", faq_theme: "preis", faq_unique_q_count: 5 },
    { slug: "wintergarten-systeme", block_1_content: "Wintergarten und Pergola unterscheiden sich grundlegend in Nutzung und Bauweise. Diese Seite hilft, die passende Lösung für Ganzjahres- oder Übergangsnutzung zu wählen.", block_2_content: "Risiken entstehen durch falsche Erwartungen an Dämmung und Wintertauglichkeit.", block_1_placement: "after_intro", block_2_placement: "before_faq", cta_primary_text: "System prüfen", cta_secondary_text: "—", faq_theme: "vergleich", faq_unique_q_count: 5 },
    { slug: "wintergarten-systeme/kaltwintergarten", block_1_content: "Ein Kaltwintergarten ist kosteneffizient für Übergangszeiten. Diese Seite hilft zu prüfen, ob diese Lösung für Ihre Nutzung ausreicht.", block_2_content: "Risiken liegen bei Frost, fehlender Isolierung und eingeschränkter Nutzung im Winter.", block_1_placement: "after_intro", block_2_placement: "before_faq", cta_primary_text: "Beratung prüfen", cta_secondary_text: "—", faq_theme: "winter", faq_unique_q_count: 5 },
    { slug: "wintergarten-systeme/glasschiebewand", block_1_content: "Glasschiebewände schaffen Wind- und Wetterschutz bei offener Nutzung. Diese Seite hilft zu entscheiden, wann sie sinnvoll ergänzen.", block_2_content: "Risiken entstehen durch minderwertige Lauftechnik oder unzureichende Dichtigkeit.", block_1_placement: "after_features", block_2_placement: "before_faq", cta_primary_text: "Lösung bewerten", cta_secondary_text: "—", faq_theme: "glas", faq_unique_q_count: 5 },
    { slug: "wintergarten-systeme/montage", block_1_content: "Die Montage eines Wintergartens stellt andere Anforderungen als eine Pergola. Glas, Anschlüsse und Abdichtung müssen präzise zusammenspielen. Diese Seite beschreibt, worauf es bei der Montage ankommt, damit Funktion und Sicherheit langfristig gewährleistet bleiben.", block_2_content: "Risiken entstehen durch unsachgemäßes Glas-Handling, fehlerhafte Anschlüsse oder fehlende Erfahrung. Das führt zu Undichtigkeiten oder Schäden an der Bausubstanz.", block_1_placement: "after_intro", block_2_placement: "before_cta", cta_primary_text: "Ablauf klären", cta_secondary_text: "—", faq_theme: "montage", faq_unique_q_count: 5 },
    { slug: "wintergarten-systeme/polen-preise", block_1_content: "Importangebote wirken oft günstiger, unterscheiden sich aber deutlich bei Gewährleistung und Service. Diese Seite hilft, Preise realistisch zu vergleichen und die langfristigen Konsequenzen zu bewerten.", block_2_content: "Risiken liegen bei fehlenden Ansprechpartnern, Ersatzteilen oder rechtlicher Durchsetzung im Schadensfall.", block_1_placement: "after_intro", block_2_placement: "before_cta", cta_primary_text: "Beratung anfragen", cta_secondary_text: "—", faq_theme: "import", faq_unique_q_count: 5 },
    { slug: "zip-screen-systeme", block_1_content: "Zip-Screen-Systeme sind für windstabile Beschattung und Sichtschutz konzipiert. Diese Seite hilft zu entscheiden, ob ein Screen-System besser passt als eine klassische Markise.", block_2_content: "Risiken entstehen, wenn Einsatzbereich und Windlast unterschätzt werden. Nicht jedes System ist für jede Lage geeignet.", block_1_placement: "after_intro", block_2_placement: "before_faq", cta_primary_text: "System prüfen", cta_secondary_text: "—", faq_theme: "screen", faq_unique_q_count: 5 },
    { slug: "zip-screen-systeme/senkrechtmarkise", block_1_content: "Senkrechtmarkisen eignen sich zur gezielten Verschattung von Fassaden und Terrassen. Diese Seite hilft, den Einsatz nach Sonnenstand und Sichtbedarf zu bewerten.", block_2_content: "Risiken bestehen bei unzureichender Führung oder falscher Montage, was zu Geräuschen und Verschleiß führt.", block_1_placement: "after_features", block_2_placement: "before_faq", cta_primary_text: "Lösung bewerten", cta_secondary_text: "—", faq_theme: "markise", faq_unique_q_count: 5 },
    { slug: "zip-screen-systeme/terrasse", block_1_content: "Für Terrassen schaffen Zip-Screens zusätzlichen Wind- und Sichtschutz. Diese Seite zeigt, wann Seitenbeschattung den Aufenthaltskomfort deutlich erhöht.", block_2_content: "Risiken entstehen durch falsche Befestigung oder fehlende Abstimmung mit bestehenden Konstruktionen.", block_1_placement: "after_intro", block_2_placement: "before_faq", cta_primary_text: "Projekt prüfen", cta_secondary_text: "—", faq_theme: "terrasse", faq_unique_q_count: 5 },
    { slug: "zip-screen-systeme/wetterfest", block_1_content: "Wetterfest bedeutet widerstandsfähig, aber nicht grenzenlos. Diese Seite hilft, realistische Erwartungen an Wind- und Regenschutz zu entwickeln.", block_2_content: "Risiken liegen im Einsatz außerhalb der vorgesehenen Belastungsgrenzen, was die Lebensdauer verkürzt.", block_1_placement: "after_intro", block_2_placement: "before_faq", cta_primary_text: "Beratung prüfen", cta_secondary_text: "—", faq_theme: "wetter", faq_unique_q_count: 5 },
    { slug: "ueber-uns", block_1_content: "Sanper arbeitet als Familienunternehmen mit klarer Verantwortung für Planung, Fertigung und Montage. Diese Seite gibt Einblick in Arbeitsweise und Entscheidungswege.", block_2_content: "Risiken bei anonymen Anbietern sind unklare Zuständigkeiten und wechselnde Ansprechpartner.", block_1_placement: "after_intro", block_2_placement: "before_cta", cta_primary_text: "Gespräch vereinbaren", cta_secondary_text: "—", faq_theme: "unternehmen", faq_unique_q_count: 5 },
    { slug: "referenzen", block_1_content: "Referenzprojekte zeigen, wie Systeme in der Praxis genutzt werden. Diese Seite hilft, eigene Anforderungen mit realen Projekten abzugleichen.", block_2_content: "Risiken entstehen, wenn Referenzen nicht vergleichbar sind oder wichtige Details fehlen.", block_1_placement: "after_gallery", block_2_placement: "before_cta", cta_primary_text: "Projekt prüfen", cta_secondary_text: "—", faq_theme: "referenzen", faq_unique_q_count: 5 },
    { slug: "genehmigung", block_1_content: "Je nach Bauart und Standort kann eine Genehmigung erforderlich sein. Diese Seite hilft zu klären, wann das zutrifft und wie vorzugehen ist.", block_2_content: "Risiken bestehen bei verspäteter Klärung, die Projekte verzögern oder stoppen kann.", block_1_placement: "after_intro", block_2_placement: "before_cta", cta_primary_text: "Genehmigung klären", cta_secondary_text: "—", faq_theme: "recht", faq_unique_q_count: 5 },
    { slug: "wartung", block_1_content: "Wartung beeinflusst Lebensdauer und Funktion. Diese Seite hilft, den realen Wartungsaufwand richtig einzuschätzen.", block_2_content: "Risiken entstehen, wenn Wartung unterschätzt oder nicht eingeplant wird.", block_1_placement: "after_intro", block_2_placement: "before_cta", cta_primary_text: "Wartung bewerten", cta_secondary_text: "—", faq_theme: "wartung", faq_unique_q_count: 5 },
    { slug: "lieferzeit", block_1_content: "Lieferzeiten hängen von Planung, Fertigung und Montage ab. Diese Seite erklärt die wichtigsten Einflussfaktoren.", block_2_content: "Risiken entstehen durch unrealistische Erwartungen oder fehlende Abstimmung im Projektablauf.", block_1_placement: "after_intro", block_2_placement: "before_cta", cta_primary_text: "Termin klären", cta_secondary_text: "—", faq_theme: "lieferung", faq_unique_q_count: 5 },
    { slug: "kontakt", block_1_content: "Der Kontakt dient der strukturierten Klärung Ihres Projekts. Diese Seite beschreibt, wie der nächste Schritt abläuft und welche Informationen sinnvoll sind.", block_2_content: "Risiken entstehen, wenn Anforderungen unklar bleiben oder zu früh Angebote eingeholt werden.", block_1_placement: "before_form", block_2_placement: "after_form", cta_primary_text: "Rückruf anfordern", cta_secondary_text: "—", faq_theme: "kontakt", faq_unique_q_count: 3 }
];

// Load existing landing_pages.json
const jsonPath = path.join(__dirname, 'src', 'data', 'landing_pages.json');
const landingPages = JSON.parse(fs.readFileSync(jsonPath, 'utf8'));

// Create a map for quick lookup
const csvMap = new Map(csvData.map(row => [row.slug, row]));

// Merge CSV data into landing pages
let updatedCount = 0;
landingPages.forEach(page => {
    const csvRow = csvMap.get(page.slug);
    if (csvRow) {
        // Add new fields from CSV
        page.block_1_content = csvRow.block_1_content;
        page.block_2_content = csvRow.block_2_content;
        page.block_1_placement = csvRow.block_1_placement;
        page.block_2_placement = csvRow.block_2_placement;
        page.cta_primary_text = csvRow.cta_primary_text;
        page.cta_secondary_text = csvRow.cta_secondary_text;
        page.faq_theme = csvRow.faq_theme;
        page.faq_unique_q_count = csvRow.faq_unique_q_count;
        updatedCount++;
    }
});

// Write updated JSON
fs.writeFileSync(jsonPath, JSON.stringify(landingPages, null, 4), 'utf8');
console.log(`✅ Updated ${updatedCount} pages with CSV content data`);
console.log(`📄 Output: ${jsonPath}`);
